### ISSUE TITLE
NAMESPACE missing import of igraph

### ISSUE THREAD

**Issue by rdiaz02** [phillipnicol/OncoBN#2]
I think at least the following functions should be imported from igraph: ends,  incident, make_directed_graph, for example with the line
`importFrom("igraph", "ends", "incident", "make_directed_graph")`  in the NAMESPACE file.

**Comment by phillipnicol** [comment]
Temporarily added this line to `NAMESPACE` but noticed that there are other imports missing... Will try to get these added ASAP

**Comment by rdiaz02** [comment]
Thanks!
