### ISSUE TITLE
Bug in Lik.genotype under CBN model?

### ISSUE THREAD

**Issue by rdiaz02** [phillipnicol/OncoBN#4]
Under the `CBN` model the likelihoods of at least some genotypes seem incorrect.

As an example, with this model (where I have set epsilon to 0, to make it easier to see)
```
 fit0
$edgelist
 [1] "WT" "A"  "A"  "B"  "A"  "C"  "C"  "D"  "B"  "D" 

$score
[1] -682.1

$graph
IGRAPH dd4d896 DN-- 5 5 -- 
+ > attr: name (v/c)
+ > edges from dd4d896 (vertex names):
[1] WT->A A ->B A ->C C ->D B ->D

$theta
[1] 0.9787 0.3478 0.3478 0.1667

$model
[1] "CBN"

$epsilon
[1] 0

```

Doing

```
Lik.genotype(fit0, c(1, 1, 1, 1))
```

returns 0, but it should not return 0: this is a CBN model and all of the requirements for D are satisfied. The actual probability should be ` prod(theta)`.

Likewise, 
```
Lik.genotype(fit0, c(1, 1, 1, 0))
```
returns 0.1184, but it should be 

```
fit0$theta[1] * fit0$theta[2]* fit0$theta[3] * (1 - fit0$theta[4])
```
which is 0.09867.

Interestingly, `Lik.genotype(fit0, c(1, 1, 0, 0))` is correct.

I am attaching a data set that returns the above fit (but with an epsilon of 0.01064). I run it as
```
data <- read.table("data.txt", header = TRUE)   
fitCPN(data, model = "CBN")
[data.txt](https://github.com/phillipnicol/OncoBN/files/8125190/data.txt)
```

**Comment by phillipnicol** [comment]
Thanks for catching this! There was an error in `GA_likelihood()` (which is separate from the usual procedure used to fit the model). I *think* this is the only issue but I am going to double check everything to make sure. 

Using the data you provided I now get the correct result. Let me know if it works on your end, thanks! 

```
> fit <- fitCPN(data,model="CBN",epsilon=0.01064,verbose=FALSE)
> fit$epsilon <- 0
> 
> Lik.genotype(fit,genotype=c(1,1,1,1)) == prod(fit$theta)
[1] TRUE
> 
> Lik.genotype(fit, c(1,1,1,0))
[1] 0.09867407
```

**Comment by rdiaz02** [comment]
Thanks!! It does work on my end (I tested all the genotypes under that example). Closing it.
